In [17]:
import torch
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

#### Multiple Linear Regression with multi output

In [190]:
# 7 input 3 output
X, y  = make_regression(n_samples=500,n_features=7,n_informative=7,n_targets=3,bias=25,noise=20,random_state=13)

In [191]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=13)

In [192]:
X_train = torch.from_numpy(X_train)
y_train = torch.from_numpy(y_train)
X_test = torch.from_numpy(X_test)
y_test = torch.from_numpy(y_test)

In [193]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr = LinearRegression()
lr.fit(X_train,y_train)
y_predLR = lr.predict(X_test)

In [194]:
r2_score(y_test,y_predLR)

0.9816225295381956

In [195]:
lr.coef_

array([[65.62386914, 50.98342248, 91.8704951 , 29.09756306, 59.38887619,
         4.20446472, 54.8564364 ],
       [ 8.6274954 , 61.89337578, 98.08826114, 14.85498841, 29.02945762,
        31.42434961, 58.00218984],
       [86.47409391, 52.53801642, 11.1883771 , 39.63969653, 19.08273696,
        94.83906132, 49.41689617]])

In [196]:
lr.intercept_

array([25.1496413 , 25.50028908, 24.6615854 ])

In [244]:
class GDClass:
    def __init__(self, epochs, lr):
        self.epochs = epochs
        self.lr = lr
        self.intercept = None
        self.coeff = None
    
    def fit(self, X_train, y_train):
        samples = X_train.shape[0]
        features = X_train.shape[1]
        target = y_train.shape[1]
        self.coeff = torch.randn((features,target),dtype=float)
        self.intercept = torch.randn((1,target),dtype=float)
        for i in range(self.epochs):
            y_hat = (X_train @ self.coeff) + self.intercept
            err = y_train - y_hat
            grad_coeff = -2 * ( X_train.T @ err) / samples # derivative of loss func wrt coeff
            grad_intercept = -2 * torch.mean(err,dim=0) # derivatitve of loss func wrt intercept
            self.coeff = self.coeff - self.lr * grad_coeff
            self.intercept = self.intercept - self.lr * grad_intercept
    
    def predict(self,X_test):
        y_pred = (X_test @ self.coeff) + self.intercept
        return y_pred

In [245]:
mygd = GDClass(100,0.1)
mygd.fit(X_train, y_train)

In [246]:
y_predGD = mygd.predict(X_test)
r2_score(y_test,y_predGD)

0.981622530310743

In [247]:
mygd.coeff

tensor([[65.6239,  8.6275, 86.4741],
        [50.9834, 61.8934, 52.5380],
        [91.8705, 98.0883, 11.1884],
        [29.0976, 14.8550, 39.6397],
        [59.3889, 29.0295, 19.0827],
        [ 4.2045, 31.4244, 94.8391],
        [54.8564, 58.0022, 49.4169]], dtype=torch.float64)

In [248]:
mygd.intercept

tensor([[25.1496, 25.5003, 24.6616]], dtype=torch.float64)

We can see that the metrics match