In [1]:
import torch
import torch.nn as nn

Mean Absolute Error (MAE) - L1 Loss

In [4]:
input  = torch.randn(3,5)
target = torch.randn(3,5)

mae_loss = nn.L1Loss()
output = mae_loss(input, target)
# output.backward()
print(input)
print(target)
print(output)

tensor([[ 1.4083, -0.5297, -1.5312, -0.2423, -0.4775],
        [ 0.3862, -0.2879, -0.2333,  0.8464,  1.8486],
        [ 0.3153,  0.2495, -0.7339, -0.0361, -1.4031]])
tensor([[-0.1277,  0.4205, -1.9512,  2.3148,  0.6054],
        [-0.4226,  1.2950, -1.6718,  1.3837,  1.5256],
        [ 0.5567,  0.7559, -0.4835,  2.2668,  0.6667]])
tensor(1.1072)


Mean Squared Error (MSE)

In [5]:
mse_loss = nn.MSELoss()
output = mse_loss(input,target)
print(input)
print(target)
print(output)

tensor([[ 1.4083, -0.5297, -1.5312, -0.2423, -0.4775],
        [ 0.3862, -0.2879, -0.2333,  0.8464,  1.8486],
        [ 0.3153,  0.2495, -0.7339, -0.0361, -1.4031]])
tensor([[-0.1277,  0.4205, -1.9512,  2.3148,  0.6054],
        [-0.4226,  1.2950, -1.6718,  1.3837,  1.5256],
        [ 0.5567,  0.7559, -0.4835,  2.2668,  0.6667]])
tensor(1.7824)


During training of a model, the loss value shoud keep on decreasing for the model to keep getting better