In [1]:
import numpy as np

Basics

In [3]:
# np.array
a = np.array([1,2,3,4,5])
print(type(a))
print(a)
#this is called a Vector (1d array)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
# 2d and 3d
b = np.array([[1,2,3],[4,5,6]])
b
# this is called a Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
bwrong =  np.array([[1,2,3],[5,6]]) #wrong shape
bwrong

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
c
# tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
# To specify data type
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [12]:
np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [13]:
# complex number
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
# float
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# To generate a sequence of nos - arange
np.arange(1,20,3) # generate 1 to 19 with a step of 3

array([ 1,  4,  7, 10, 13, 16, 19])

In [20]:
# Using reshape
np.arange(1,11).reshape(5,2) # row,col

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [21]:
np.arange(1,11).reshape(2,5) # row,col

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
# Note that row *  col should be equal to number of elements
np.arange(1,12).reshape(5,2) # row,col

ValueError: cannot reshape array of size 11 into shape (5,2)

In [23]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# np.ones and np.zeros are used to initialize arrays in nn (weights)

In [30]:
# to generate random values
np.random.random((3,4))

array([[0.13232538, 0.46124832, 0.05291963, 0.00360615],
       [0.31085339, 0.23402283, 0.32803258, 0.48000742],
       [0.80648926, 0.5620866 , 0.84569465, 0.97801566]])

In [38]:
# To generate a nparray whose values are linearly split in a range
np.linspace(-10,10,10)
# (low,high,n) n is the no. of numbers to be generated
# used in ml algo plots

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [41]:
np.linspace(-10,10,21).reshape((3,7))

array([[-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.],
       [ -3.,  -2.,  -1.,   0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [42]:
# Generate an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [44]:
vector = np.arange(10)
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
matrix = np.arange(12,dtype=float).reshape(3,4)
matrix

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [69]:
tensor = np.arange(8).reshape(2,2,2)
tensor

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
# Dimensions
vector.ndim

1

In [71]:
matrix.ndim

2

In [72]:
tensor.ndim

3

In [73]:
np.arange(16).reshape(2,2,2,2).ndim


4

In [74]:
vector.shape

(10,)

In [75]:
matrix.shape

(3, 4)

In [76]:
tensor.shape

(2, 2, 2)

In [77]:
vector.size

10

In [78]:
matrix.size

12

In [79]:
tensor.size

8

In [84]:
# To see how much memory is occupied by one item of the array
# Since its int/float in all dims, it shows 8bytes
vector.itemsize

8

In [85]:
matrix.itemsize

8

In [86]:
tensor.itemsize

8

In [87]:
# datatype
vector.dtype

dtype('int64')

In [88]:
matrix.dtype

dtype('float64')

In [89]:
tensor.dtype

dtype('int64')

In [91]:
# To change datatype
# This is done sometimes to reduce the size
# Also called as quantization
matrix.astype(np.int32)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)

Scalar Operations

In [92]:
# arithmetic
vector * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [93]:
matrix + 2

array([[ 2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.]])

In [94]:
tensor / 2

array([[[0. , 0.5],
        [1. , 1.5]],

       [[2. , 2.5],
        [3. , 3.5]]])

In [95]:
# Relational
vector > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [96]:
matrix == 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

Vector Operations (works on same shape only)

In [97]:
vector + matrix

ValueError: operands could not be broadcast together with shapes (10,) (3,4) 

In [98]:
a = np.arange(10)
b = np.arange(10,20)

In [99]:
# arithmetic
a + b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [100]:
a * b

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [101]:
a / b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [102]:
b / a

/tmp/ipykernel_267220/1491818542.py:1: RuntimeWarning: divide by zero encountered in divide
  b / a


array([        inf, 11.        ,  6.        ,  4.33333333,  3.5       ,
        3.        ,  2.66666667,  2.42857143,  2.25      ,  2.11111111])

Array Functions

In [112]:
a = np.random.random((3,3))
a

array([[0.17610915, 0.37218975, 0.0772613 ],
       [0.06000673, 0.48934789, 0.50709481],
       [0.87888245, 0.28513906, 0.45746955]])

In [113]:
a = np.round(a * 100)
a

array([[18., 37.,  8.],
       [ 6., 49., 51.],
       [88., 29., 46.]])

In [114]:
np.max(a)

np.float64(88.0)

In [115]:
np.sum(a)

np.float64(332.0)

In [116]:
np.prod(a)

np.float64(9378215852544.0)

In [117]:
# You mentioned axis=0 means columns and axis=1 means rows. However, in the documentation, it mentions axis=0 means rows and axis=1 means columns. But the behavior of some functions such as min,max,sum,mean,std,var doesn't follow the convention of documentation. The reason for that is: the default behavior of these methods is to calculate these values for each column. This is because the columns are the features or variables in the dataset, and it is often more useful to know these values for each feature than these values for each row. But if you see other functions such as np.append or np.unique, here axis=0 indeed means rows. Besides, in pandas we always use index as axis=0 and columns as axis=1.

In [118]:
np.max(a,axis=0) #col

array([88., 49., 51.])

In [119]:
np.max(a,axis=1) #row

array([37., 51., 88.])

In [120]:
np.mean(a)

np.float64(36.888888888888886)

In [121]:
np.median(a)

np.float64(37.0)

In [123]:
np.std(a)

np.float64(24.149738643372725)

In [124]:
np.var(a)

np.float64(583.2098765432099)

In [125]:
# Trig funcs
np.sin(a)

array([[-0.75098725, -0.64353813,  0.98935825],
       [-0.2794155 , -0.95375265,  0.67022918],
       [ 0.0353983 , -0.66363388,  0.90178835]])

In [126]:
# Dot product
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [127]:
np.dot(a2,a1)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [129]:
np.log(a)

array([[2.89037176, 3.61091791, 2.07944154],
       [1.79175947, 3.8918203 , 3.93182563],
       [4.47733681, 3.36729583, 3.8286414 ]])

In [130]:
np.exp(a)

array([[6.56599691e+07, 1.17191424e+16, 2.98095799e+03],
       [4.03428793e+02, 1.90734657e+21, 1.40934908e+22],
       [1.65163625e+38, 3.93133430e+12, 9.49611942e+19]])

Indexing and Slicing

In [132]:
vector,matrix,tensor

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [133]:
vector[0]

np.int64(0)

In [134]:
matrix[1][2]

np.float64(6.0)

In [135]:
matrix[1,2]

np.float64(6.0)

In [136]:
matrix[1,2,3]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [137]:
tensor[1,0,1]

np.int64(5)

In [148]:
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
vector[2:5] #slicing

array([2, 3, 4])

In [143]:
vector[2:5:2]

array([2, 4])

In [147]:
matrix

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [144]:
matrix[0,:]

array([0., 1., 2., 3.])

In [145]:
matrix[1:3,2:4]

array([[ 6.,  7.],
       [10., 11.]])

In [146]:
matrix[:,2]

array([ 2.,  6., 10.])

In [150]:
matrix[::2,:3] #provide step

array([[ 0.,  1.,  2.],
       [ 8.,  9., 10.]])

In [157]:
tensor[:,:,::2]

array([[[0],
        [2]],

       [[4],
        [6]]])

Iterating

In [158]:
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
for i in vector:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [160]:
matrix

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [161]:
for i in matrix:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [162]:
for i in np.nditer(matrix):
    print(i)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


Reshaping

In [163]:
matrix

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [164]:
# Transpose
matrix.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [165]:
vector.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
tensor = np.arange(27).reshape(3,3,3)
tensor

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [169]:
tensor.T

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [170]:
matrix.transpose()

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [177]:
# To change any dim to single array- ravel
matrix.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [178]:
tensor.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [185]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4) #must match dimensions

In [186]:
# Horizontal Stacking
np.hstack((a,b))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [187]:
# Vertical Stacking
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting, split it, hsplit, vsplit

Advanced Indexing

In [2]:
import numpy as np

In [5]:
# Normal Indexing and slicing
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a[1,2]

np.int64(8)

In [6]:
# Fancy Indexing
# Used when pattern is not formed
a[[0,2,3]]

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
a[:,[3,5]]

array([[ 3,  5],
       [ 9, 11],
       [15, 17],
       [21, 23]])

In [8]:
# Boolean Indexing
# Indexing on the basis of some logic
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[48, 71, 96, 87],
       [ 1, 86, 83, 44],
       [33, 32, 58,  3],
       [76, 18, 36, 84],
       [88, 28, 95, 20],
       [56, 83,  2, 79]])

In [9]:
# Boolean mask generation
# Find all nos > 50
a > 50

array([[False,  True,  True,  True],
       [False,  True,  True, False],
       [False, False,  True, False],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [ True,  True, False,  True]])

In [10]:
# Now mask it with the original matrix
a[a > 50]

array([71, 96, 87, 86, 83, 58, 76, 84, 88, 95, 56, 83, 79])

In [11]:
# Find even nos
a[a % 2 == 0]

array([48, 96, 86, 44, 32, 58, 76, 18, 36, 84, 88, 28, 20, 56,  2])

In [12]:
# Find nos > 50 and even
a[(a % 2 == 0) & (a > 50)]

array([96, 86, 58, 76, 84, 88, 56])

In [13]:
# Using bitwise ops only works, not the logical operators
a[(a % 2 == 0) and (a > 50)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [14]:
# All nos, not div by 7
a[~(a % 7 == 0)]

array([48, 71, 96, 87,  1, 86, 83, 44, 33, 32, 58,  3, 76, 18, 36, 88, 95,
       20, 83,  2, 79])

##### Broadcasting  
- It describes how numpy treats arrays of different shape during arithmetic operations
- The smaller array is "broadcast" across the larger array so that they have compatible shapes
- It's used in vectorization

- Normally, numpy operations are vectorized, but if we use different shapes, then it's not possible for a direct vectorization (refer numpy optimization article in notebook).
- So to achieve this, we use broadcasting, i.e. if the the numpy arrays are of same size, then we'll be able to do vectorized operations

In [17]:
# Same shape

a = np.arange(24).reshape(6,4)
b = np.arange(24,48).reshape(6,4)

print(a)
print(b)

print(a + b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
[[24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]
 [48 50 52 54]
 [56 58 60 62]
 [64 66 68 70]]


In [26]:
# Different shape
a = np.arange(24).reshape(6,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

a + b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (6,4) (4,3) 

In [27]:
a = np.arange(24).reshape(6,4)
b = np.arange(4).reshape(1,4)

print(a)
print(b)

a + b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[0 1 2 3]]


array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18],
       [16, 18, 20, 22],
       [20, 22, 24, 26]])

In [31]:
a = np.arange(24).reshape(6,4)
b = np.arange(6).reshape(6,1)

print(a)
print(b)

a + b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23],
       [25, 26, 27, 28]])

In [32]:
a = np.arange(24).reshape(6,4)
b = np.arange(6)

print(a)
print(b)

a + b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[0 1 2 3 4 5]


ValueError: operands could not be broadcast together with shapes (6,4) (6,) 

In [33]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

a + b

[[0 1 2]]
[[0]
 [1]
 [2]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [34]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

a + b

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])