In [1]:
import torch

### Creating Tensors

In [7]:
# Creating empty tensor
x = torch.empty(3,4)
print(type(x))
print(x)
# Here we can see that its filled with garbage values like C

<class 'torch.Tensor'>
tensor([[4.9970e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [       nan, 5.0778e+31, 7.3909e+22, 4.5120e+27],
        [7.0062e+22, 4.5144e+27, 1.7438e+19, 1.8888e+31]])


In [11]:
# Usually we initialize it with zeros or ones
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
# Generated random floats btw 0 and 1
random_btw_01 = torch.rand(3,4)
random_btw_01

tensor([[0.8866, 0.2793, 0.9174, 0.1613],
        [0.3339, 0.3471, 0.9122, 0.5155],
        [0.7929, 0.1628, 0.1221, 0.5188]])

In [21]:
# Now usually the random initialization is used by model weights as a starting point in their training
# In research, to have some assurance of reproducibility, we use the random generators seed
torch.manual_seed(1729)
random1 = torch.rand(3,4)
random1
# No matter how many times random1 is initialized, it stays the same

tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938]])

In [24]:
random2 = torch.rand(3,4)
random2 
# the seed resets to produce a diff set

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614],
        [0.6493, 0.2633, 0.4762, 0.0548]])

In [25]:
torch.manual_seed(1729)
random3 = torch.rand(3,4)
random3
# Now this produces same as random1

tensor([[0.3126, 0.3791, 0.3087, 0.0736],
        [0.4216, 0.0691, 0.2332, 0.4047],
        [0.2162, 0.9927, 0.4128, 0.5938]])

In [30]:
# Tensor shapes
# torch.*_like() methods to create tensor

x = torch.empty(2,2,3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[4.5918e-35, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 4.2160e-01, 6.9054e-02]],

        [[2.3322e-01, 4.0466e-01, 2.1624e-01],
         [9.9269e-01, 4.1275e-01, 5.9382e-01]]])


In [31]:
empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

torch.Size([2, 2, 3])
tensor([[[4.5925e-35, 0.0000e+00, 0.0000e+00],
         [0.0000e+00,        nan, 6.9054e-02]],

        [[1.7753e+28, 4.4339e+27, 1.7975e+19],
         [6.9481e+22, 5.5757e-02, 1.8728e+31]]])


In [32]:
zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [34]:
# torch.tensor() method to create tensor
# similar to np.array()
# It creates a copy of data

x = torch.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [38]:
# Create tensors with datatypes
a = torch.ones((2,3),dtype=torch.int16)
a

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [48]:
b = torch.rand((2,3),dtype=torch.float64) * 20
b

tensor([[ 2.4081,  5.3389, 13.8556],
        [ 9.2452,  1.6418, 13.6600]], dtype=torch.float64)

In [49]:
c = b.to(torch.int32)
c

tensor([[ 2,  5, 13],
        [ 9,  1, 13]], dtype=torch.int32)