In [1]:
import numpy as np

Basics

In [3]:
# np.array
a = np.array([1,2,3,4,5])
print(type(a))
print(a)
#this is called a Vector (1d array)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
# 2d and 3d
b = np.array([[1,2,3],[4,5,6]])
b
# this is called a Matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
bwrong =  np.array([[1,2,3],[5,6]]) #wrong shape
bwrong

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [9]:
c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
c
# tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
# To specify data type
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [12]:
np.array([1,0,3],dtype=bool)

array([ True, False,  True])

In [13]:
# complex number
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
# float
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# To generate a sequence of nos - arange
np.arange(1,20,3) # generate 1 to 19 with a step of 3

array([ 1,  4,  7, 10, 13, 16, 19])

In [20]:
# Using reshape
np.arange(1,11).reshape(5,2) # row,col

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [21]:
np.arange(1,11).reshape(2,5) # row,col

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
# Note that row *  col should be equal to number of elements
np.arange(1,12).reshape(5,2) # row,col

ValueError: cannot reshape array of size 11 into shape (5,2)

In [23]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# np.ones and np.zeros are used to initialize arrays in nn (weights)

In [30]:
# to generate random values
np.random.random((3,4))

array([[0.13232538, 0.46124832, 0.05291963, 0.00360615],
       [0.31085339, 0.23402283, 0.32803258, 0.48000742],
       [0.80648926, 0.5620866 , 0.84569465, 0.97801566]])

In [38]:
# To generate a nparray whose values are linearly split in a range
np.linspace(-10,10,10)
# (low,high,n) n is the no. of numbers to be generated
# used in ml algo plots

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [41]:
np.linspace(-10,10,21).reshape((3,7))

array([[-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.],
       [ -3.,  -2.,  -1.,   0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [42]:
# Generate an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])